// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        (unknown)
// source: df_1002.proto

package com_ss_pb_proto

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type PItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Idx    *int32  `protobuf:"varint,1,opt,name=idx" json:"idx,omitempty"`                     // 容器位置索引
	ItemId *uint32 `protobuf:"varint,2,opt,name=item_id,json=itemId" json:"item_id,omitempty"` // 物品ID
	Count  *uint32 `protobuf:"varint,3,opt,name=count" json:"count,omitempty"`                 // 物品数量 (用作刷新时 为0的情况, 清空该位置的物品)
}

func (x *PItem) Reset() {
	*x = PItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_df_1002_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PItem) ProtoMessage() {}

func (x *PItem) ProtoReflect() protoreflect.Message {
	mi := &file_df_1002_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PItem.ProtoReflect.Descriptor instead.
func (*PItem) Descriptor() ([]byte, []int) {
	return file_df_1002_proto_rawDescGZIP(), []int{0}
}

func (x *PItem) GetIdx() int32 {
	if x != nil && x.Idx != nil {
		return *x.Idx
	}
	return 0
}

func (x *PItem) GetItemId() uint32 {
	if x != nil && x.ItemId != nil {
		return *x.ItemId
	}
	return 0
}

func (x *PItem) GetCount() uint32 {
	if x != nil && x.Count != nil {
		return *x.Count
	}
	return 0
}

type P_Reward2 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ItemId *uint32 `protobuf:"varint,1,opt,name=item_id,json=itemId" json:"item_id,omitempty"` // 物品ID
	ObjId  *uint32 `protobuf:"varint,2,opt,name=obj_id,json=objId" json:"obj_id,omitempty"`    // 对象ID(可能没有对象,没有时为0)
	Count  *uint32 `protobuf:"varint,3,opt,name=count" json:"count,omitempty"`                 // 物品数量
}

func (x *P_Reward2) Reset() {
	*x = P_Reward2{}
	if protoimpl.UnsafeEnabled {
		mi := &file_df_1002_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *P_Reward2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*P_Reward2) ProtoMessage() {}

func (x *P_Reward2) ProtoReflect() protoreflect.Message {
	mi := &file_df_1002_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use P_Reward2.ProtoReflect.Descriptor instead.
func (*P_Reward2) Descriptor() ([]byte, []int) {
	return file_df_1002_proto_rawDescGZIP(), []int{1}
}

func (x *P_Reward2) GetItemId() uint32 {
	if x != nil && x.ItemId != nil {
		return *x.ItemId
	}
	return 0
}

func (x *P_Reward2) GetObjId() uint32 {
	if x != nil && x.ObjId != nil {
		return *x.ObjId
	}
	return 0
}

func (x *P_Reward2) GetCount() uint32 {
	if x != nil && x.Count != nil {
		return *x.Count
	}
	return 0
}

type P_Reward2_List struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Reward2 []*P_Reward2 `protobuf:"bytes,1,rep,name=reward2" json:"reward2,omitempty"` // 归类好的物品列表
}

func (x *P_Reward2_List) Reset() {
	*x = P_Reward2_List{}
	if protoimpl.UnsafeEnabled {
		mi := &file_df_1002_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *P_Reward2_List) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*P_Reward2_List) ProtoMessage() {}

func (x *P_Reward2_List) ProtoReflect() protoreflect.Message {
	mi := &file_df_1002_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use P_Reward2_List.ProtoReflect.Descriptor instead.
func (*P_Reward2_List) Descriptor() ([]byte, []int) {
	return file_df_1002_proto_rawDescGZIP(), []int{2}
}

func (x *P_Reward2_List) GetReward2() []*P_Reward2 {
	if x != nil {
		return x.Reward2
	}
	return nil
}

type P_Bag_Limit struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BagType *uint32 `protobuf:"varint,1,opt,name=bag_type,json=bagType" json:"bag_type,omitempty"` // 背包类型
	Limit   *uint32 `protobuf:"varint,2,opt,name=limit" json:"limit,omitempty"`                    // 容量上限
}

func (x *P_Bag_Limit) Reset() {
	*x = P_Bag_Limit{}
	if protoimpl.UnsafeEnabled {
		mi := &file_df_1002_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *P_Bag_Limit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*P_Bag_Limit) ProtoMessage() {}

func (x *P_Bag_Limit) ProtoReflect() protoreflect.Message {
	mi := &file_df_1002_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use P_Bag_Limit.ProtoReflect.Descriptor instead.
func (*P_Bag_Limit) Descriptor() ([]byte, []int) {
	return file_df_1002_proto_rawDescGZIP(), []int{3}
}

func (x *P_Bag_Limit) GetBagType() uint32 {
	if x != nil && x.BagType != nil {
		return *x.BagType
	}
	return 0
}

func (x *P_Bag_Limit) GetLimit() uint32 {
	if x != nil && x.Limit != nil {
		return *x.Limit
	}
	return 0
}

// 登录发送背包类型信息
type Sc_10020000 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BagLimits []*P_Bag_Limit `protobuf:"bytes,1,rep,name=bag_limits,json=bagLimits" json:"bag_limits,omitempty"` // 背包类型信息
}

func (x *Sc_10020000) Reset() {
	*x = Sc_10020000{}
	if protoimpl.UnsafeEnabled {
		mi := &file_df_1002_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Sc_10020000) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sc_10020000) ProtoMessage() {}

func (x *Sc_10020000) ProtoReflect() protoreflect.Message {
	mi := &file_df_1002_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sc_10020000.ProtoReflect.Descriptor instead.
func (*Sc_10020000) Descriptor() ([]byte, []int) {
	return file_df_1002_proto_rawDescGZIP(), []int{4}
}

func (x *Sc_10020000) GetBagLimits() []*P_Bag_Limit {
	if x != nil {
		return x.BagLimits
	}
	return nil
}

// 获取背包物品列表
type Cs_10020001 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BagType *uint32 `protobuf:"varint,1,opt,name=bag_type,json=bagType" json:"bag_type,omitempty"` // 背包类型
}

func (x *Cs_10020001) Reset() {
	*x = Cs_10020001{}
	if protoimpl.UnsafeEnabled {
		mi := &file_df_1002_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Cs_10020001) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cs_10020001) ProtoMessage() {}

func (x *Cs_10020001) ProtoReflect() protoreflect.Message {
	mi := &file_df_1002_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cs_10020001.ProtoReflect.Descriptor instead.
func (*Cs_10020001) Descriptor() ([]byte, []int) {
	return file_df_1002_proto_rawDescGZIP(), []int{5}
}

func (x *Cs_10020001) GetBagType() uint32 {
	if x != nil && x.BagType != nil {
		return *x.BagType
	}
	return 0
}

type Sc_10020001 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BagType *uint32  `protobuf:"varint,1,opt,name=bag_type,json=bagType" json:"bag_type,omitempty"` // 背包类型
	Items   []*PItem `protobuf:"bytes,2,rep,name=items" json:"items,omitempty"`                     // 物品的列表
}

func (x *Sc_10020001) Reset() {
	*x = Sc_10020001{}
	if protoimpl.UnsafeEnabled {
		mi := &file_df_1002_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Sc_10020001) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sc_10020001) ProtoMessage() {}

func (x *Sc_10020001) ProtoReflect() protoreflect.Message {
	mi := &file_df_1002_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sc_10020001.ProtoReflect.Descriptor instead.
func (*Sc_10020001) Descriptor() ([]byte, []int) {
	return file_df_1002_proto_rawDescGZIP(), []int{6}
}

func (x *Sc_10020001) GetBagType() uint32 {
	if x != nil && x.BagType != nil {
		return *x.BagType
	}
	return 0
}

func (x *Sc_10020001) GetItems() []*PItem {
	if x != nil {
		return x.Items
	}
	return nil
}

// 使用物品
type Cs_10020002 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BagType *uint32 `protobuf:"varint,1,opt,name=bag_type,json=bagType" json:"bag_type,omitempty"` // 背包类型
	Idx     *int32  `protobuf:"varint,2,opt,name=idx" json:"idx,omitempty"`                        // 容器位置索引
	ObjId   *uint32 `protobuf:"varint,3,opt,name=obj_id,json=objId" json:"obj_id,omitempty"`       // 对象ID
	Count   *uint32 `protobuf:"varint,4,opt,name=count" json:"count,omitempty"`                    // 使用数量
}

func (x *Cs_10020002) Reset() {
	*x = Cs_10020002{}
	if protoimpl.UnsafeEnabled {
		mi := &file_df_1002_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Cs_10020002) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cs_10020002) ProtoMessage() {}

func (x *Cs_10020002) ProtoReflect() protoreflect.Message {
	mi := &file_df_1002_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cs_10020002.ProtoReflect.Descriptor instead.
func (*Cs_10020002) Descriptor() ([]byte, []int) {
	return file_df_1002_proto_rawDescGZIP(), []int{7}
}

func (x *Cs_10020002) GetBagType() uint32 {
	if x != nil && x.BagType != nil {
		return *x.BagType
	}
	return 0
}

func (x *Cs_10020002) GetIdx() int32 {
	if x != nil && x.Idx != nil {
		return *x.Idx
	}
	return 0
}

func (x *Cs_10020002) GetObjId() uint32 {
	if x != nil && x.ObjId != nil {
		return *x.ObjId
	}
	return 0
}

func (x *Cs_10020002) GetCount() uint32 {
	if x != nil && x.Count != nil {
		return *x.Count
	}
	return 0
}

// 物品列表刷新
type Sc_10020002 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BagType *uint32  `protobuf:"varint,1,opt,name=bag_type,json=bagType" json:"bag_type,omitempty"` // 背包类型
	Items   []*PItem `protobuf:"bytes,2,rep,name=items" json:"items,omitempty"`                     // 物品的列表
}

func (x *Sc_10020002) Reset() {
	*x = Sc_10020002{}
	if protoimpl.UnsafeEnabled {
		mi := &file_df_1002_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Sc_10020002) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sc_10020002) ProtoMessage() {}

func (x *Sc_10020002) ProtoReflect() protoreflect.Message {
	mi := &file_df_1002_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sc_10020002.ProtoReflect.Descriptor instead.
func (*Sc_10020002) Descriptor() ([]byte, []int) {
	return file_df_1002_proto_rawDescGZIP(), []int{8}
}

func (x *Sc_10020002) GetBagType() uint32 {
	if x != nil && x.BagType != nil {
		return *x.BagType
	}
	return 0
}

func (x *Sc_10020002) GetItems() []*PItem {
	if x != nil {
		return x.Items
	}
	return nil
}

// 礼包拆解效果
type Sc_10020003 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Reward2List []*P_Reward2_List `protobuf:"bytes,1,rep,name=reward2_list,json=reward2List" json:"reward2_list,omitempty"` // 效果物品列表
}

func (x *Sc_10020003) Reset() {
	*x = Sc_10020003{}
	if protoimpl.UnsafeEnabled {
		mi := &file_df_1002_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Sc_10020003) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sc_10020003) ProtoMessage() {}

func (x *Sc_10020003) ProtoReflect() protoreflect.Message {
	mi := &file_df_1002_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sc_10020003.ProtoReflect.Descriptor instead.
func (*Sc_10020003) Descriptor() ([]byte, []int) {
	return file_df_1002_proto_rawDescGZIP(), []int{9}
}

func (x *Sc_10020003) GetReward2List() []*P_Reward2_List {
	if x != nil {
		return x.Reward2List
	}
	return nil
}

// 改名(需要消耗一张改名卡)
type Cs_10020004 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uname *string `protobuf:"bytes,1,opt,name=uname" json:"uname,omitempty"`
}

func (x *Cs_10020004) Reset() {
	*x = Cs_10020004{}
	if protoimpl.UnsafeEnabled {
		mi := &file_df_1002_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Cs_10020004) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cs_10020004) ProtoMessage() {}

func (x *Cs_10020004) ProtoReflect() protoreflect.Message {
	mi := &file_df_1002_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cs_10020004.ProtoReflect.Descriptor instead.
func (*Cs_10020004) Descriptor() ([]byte, []int) {
	return file_df_1002_proto_rawDescGZIP(), []int{10}
}

func (x *Cs_10020004) GetUname() string {
	if x != nil && x.Uname != nil {
		return *x.Uname
	}
	return ""
}

type Sc_10020004 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uname *string `protobuf:"bytes,1,opt,name=uname" json:"uname,omitempty"`
}

func (x *Sc_10020004) Reset() {
	*x = Sc_10020004{}
	if protoimpl.UnsafeEnabled {
		mi := &file_df_1002_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Sc_10020004) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sc_10020004) ProtoMessage() {}

func (x *Sc_10020004) ProtoReflect() protoreflect.Message {
	mi := &file_df_1002_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sc_10020004.ProtoReflect.Descriptor instead.
func (*Sc_10020004) Descriptor() ([]byte, []int) {
	return file_df_1002_proto_rawDescGZIP(), []int{11}
}

func (x *Sc_10020004) GetUname() string {
	if x != nil && x.Uname != nil {
		return *x.Uname
	}
	return ""
}

// 出售物品
type Cs_10020005 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BagType   *uint32  `protobuf:"varint,1,opt,name=bag_type,json=bagType" json:"bag_type,omitempty"`      // 背包类型
	SellItems []*PItem `protobuf:"bytes,2,rep,name=sell_items,json=sellItems" json:"sell_items,omitempty"` // 出售物品列表
	AsynFlag  *uint32  `protobuf:"varint,3,opt,name=asyn_flag,json=asynFlag" json:"asyn_flag,omitempty"`   // 异步标识(发什么回什么)
}

func (x *Cs_10020005) Reset() {
	*x = Cs_10020005{}
	if protoimpl.UnsafeEnabled {
		mi := &file_df_1002_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Cs_10020005) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cs_10020005) ProtoMessage() {}

func (x *Cs_10020005) ProtoReflect() protoreflect.Message {
	mi := &file_df_1002_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cs_10020005.ProtoReflect.Descriptor instead.
func (*Cs_10020005) Descriptor() ([]byte, []int) {
	return file_df_1002_proto_rawDescGZIP(), []int{12}
}

func (x *Cs_10020005) GetBagType() uint32 {
	if x != nil && x.BagType != nil {
		return *x.BagType
	}
	return 0
}

func (x *Cs_10020005) GetSellItems() []*PItem {
	if x != nil {
		return x.SellItems
	}
	return nil
}

func (x *Cs_10020005) GetAsynFlag() uint32 {
	if x != nil && x.AsynFlag != nil {
		return *x.AsynFlag
	}
	return 0
}

// 出售成功
type Sc_10020005 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BagType   *uint32      `protobuf:"varint,1,opt,name=bag_type,json=bagType" json:"bag_type,omitempty"`      // 背包类型
	SellItems []*PItem     `protobuf:"bytes,2,rep,name=sell_items,json=sellItems" json:"sell_items,omitempty"` // 出售物品列表
	AsynFlag  *uint32      `protobuf:"varint,3,opt,name=asyn_flag,json=asynFlag" json:"asyn_flag,omitempty"`   // 异步标识(发什么回什么)
	Reward    []*P_Reward2 `protobuf:"bytes,4,rep,name=reward" json:"reward,omitempty"`                        // 出售后获取的物品列表
}

func (x *Sc_10020005) Reset() {
	*x = Sc_10020005{}
	if protoimpl.UnsafeEnabled {
		mi := &file_df_1002_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Sc_10020005) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sc_10020005) ProtoMessage() {}

func (x *Sc_10020005) ProtoReflect() protoreflect.Message {
	mi := &file_df_1002_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sc_10020005.ProtoReflect.Descriptor instead.
func (*Sc_10020005) Descriptor() ([]byte, []int) {
	return file_df_1002_proto_rawDescGZIP(), []int{13}
}

func (x *Sc_10020005) GetBagType() uint32 {
	if x != nil && x.BagType != nil {
		return *x.BagType
	}
	return 0
}

func (x *Sc_10020005) GetSellItems() []*PItem {
	if x != nil {
		return x.SellItems
	}
	return nil
}

func (x *Sc_10020005) GetAsynFlag() uint32 {
	if x != nil && x.AsynFlag != nil {
		return *x.AsynFlag
	}
	return 0
}

func (x *Sc_10020005) GetReward() []*P_Reward2 {
	if x != nil {
		return x.Reward
	}
	return nil
}

// 更改性别
type Cs_10020006 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sex *uint32 `protobuf:"varint,1,opt,name=sex" json:"sex,omitempty"` // 性别
}

func (x *Cs_10020006) Reset() {
	*x = Cs_10020006{}
	if protoimpl.UnsafeEnabled {
		mi := &file_df_1002_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Cs_10020006) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cs_10020006) ProtoMessage() {}

func (x *Cs_10020006) ProtoReflect() protoreflect.Message {
	mi := &file_df_1002_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cs_10020006.ProtoReflect.Descriptor instead.
func (*Cs_10020006) Descriptor() ([]byte, []int) {
	return file_df_1002_proto_rawDescGZIP(), []int{14}
}

func (x *Cs_10020006) GetSex() uint32 {
	if x != nil && x.Sex != nil {
		return *x.Sex
	}
	return 0
}

// 更改性别成功
type Sc_10020006 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sex *uint32 `protobuf:"varint,1,opt,name=sex" json:"sex,omitempty"` // 性别
}

func (x *Sc_10020006) Reset() {
	*x = Sc_10020006{}
	if protoimpl.UnsafeEnabled {
		mi := &file_df_1002_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Sc_10020006) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sc_10020006) ProtoMessage() {}

func (x *Sc_10020006) ProtoReflect() protoreflect.Message {
	mi := &file_df_1002_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sc_10020006.ProtoReflect.Descriptor instead.
func (*Sc_10020006) Descriptor() ([]byte, []int) {
	return file_df_1002_proto_rawDescGZIP(), []int{15}
}

func (x *Sc_10020006) GetSex() uint32 {
	if x != nil && x.Sex != nil {
		return *x.Sex
	}
	return 0
}

var File_df_1002_proto protoreflect.FileDescriptor

var file_df_1002_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x64, 0x66, 0x5f, 0x31, 0x30, 0x30, 0x32, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x0f, 0x63, 0x6f, 0x6d, 0x2e, 0x73, 0x73, 0x2e, 0x70, 0x62, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x34, 0x0a, 0x05, 0x50, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x0b, 0x0a, 0x03, 0x69, 0x64, 0x78,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x12, 0x0f, 0x0a, 0x07, 0x69, 0x74, 0x65, 0x6d, 0x5f, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x12, 0x0d, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x22, 0x3b, 0x0a, 0x09, 0x50, 0x5f, 0x52, 0x65, 0x77, 0x61,
	0x72, 0x64, 0x32, 0x12, 0x0f, 0x0a, 0x07, 0x69, 0x74, 0x65, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0d, 0x12, 0x0e, 0x0a, 0x06, 0x6f, 0x62, 0x6a, 0x5f, 0x69, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0d, 0x12, 0x0d, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0d, 0x22, 0x3d, 0x0a, 0x0e, 0x50, 0x5f, 0x52, 0x65, 0x77, 0x61, 0x72, 0x64, 0x32,
	0x5f, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x2b, 0x0a, 0x07, 0x72, 0x65, 0x77, 0x61, 0x72, 0x64, 0x32,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x73, 0x73, 0x2e,
	0x70, 0x62, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x5f, 0x52, 0x65, 0x77, 0x61, 0x72,
	0x64, 0x32, 0x22, 0x2e, 0x0a, 0x0b, 0x50, 0x5f, 0x42, 0x61, 0x67, 0x5f, 0x4c, 0x69, 0x6d, 0x69,
	0x74, 0x12, 0x10, 0x0a, 0x08, 0x62, 0x61, 0x67, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0d, 0x12, 0x0d, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0d, 0x22, 0x3f, 0x0a, 0x0b, 0x53, 0x63, 0x5f, 0x31, 0x30, 0x30, 0x32, 0x30, 0x30, 0x30,
	0x30, 0x12, 0x30, 0x0a, 0x0a, 0x62, 0x61, 0x67, 0x5f, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x73, 0x73, 0x2e, 0x70,
	0x62, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x5f, 0x42, 0x61, 0x67, 0x5f, 0x4c, 0x69,
	0x6d, 0x69, 0x74, 0x22, 0x1f, 0x0a, 0x0b, 0x43, 0x73, 0x5f, 0x31, 0x30, 0x30, 0x32, 0x30, 0x30,
	0x30, 0x31, 0x12, 0x10, 0x0a, 0x08, 0x62, 0x61, 0x67, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0d, 0x22, 0x46, 0x0a, 0x0b, 0x53, 0x63, 0x5f, 0x31, 0x30, 0x30, 0x32, 0x30,
	0x30, 0x30, 0x31, 0x12, 0x10, 0x0a, 0x08, 0x62, 0x61, 0x67, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0d, 0x12, 0x25, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x73, 0x73, 0x2e, 0x70, 0x62,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x49, 0x74, 0x65, 0x6d, 0x22, 0x4b, 0x0a, 0x0b,
	0x43, 0x73, 0x5f, 0x31, 0x30, 0x30, 0x32, 0x30, 0x30, 0x30, 0x32, 0x12, 0x10, 0x0a, 0x08, 0x62,
	0x61, 0x67, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x12, 0x0b, 0x0a,
	0x03, 0x69, 0x64, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x12, 0x0e, 0x0a, 0x06, 0x6f, 0x62,
	0x6a, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x12, 0x0d, 0x0a, 0x05, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x22, 0x46, 0x0a, 0x0b, 0x53, 0x63, 0x5f,
	0x31, 0x30, 0x30, 0x32, 0x30, 0x30, 0x30, 0x32, 0x12, 0x10, 0x0a, 0x08, 0x62, 0x61, 0x67, 0x5f,
	0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x12, 0x25, 0x0a, 0x05, 0x69, 0x74,
	0x65, 0x6d, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x63, 0x6f, 0x6d, 0x2e,
	0x73, 0x73, 0x2e, 0x70, 0x62, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x49, 0x74, 0x65,
	0x6d, 0x22, 0x44, 0x0a, 0x0b, 0x53, 0x63, 0x5f, 0x31, 0x30, 0x30, 0x32, 0x30, 0x30, 0x30, 0x33,
	0x12, 0x35, 0x0a, 0x0c, 0x72, 0x65, 0x77, 0x61, 0x72, 0x64, 0x32, 0x5f, 0x6c, 0x69, 0x73, 0x74,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x73, 0x73, 0x2e,
	0x70, 0x62, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x5f, 0x52, 0x65, 0x77, 0x61, 0x72,
	0x64, 0x32, 0x5f, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x1c, 0x0a, 0x0b, 0x43, 0x73, 0x5f, 0x31, 0x30,
	0x30, 0x32, 0x30, 0x30, 0x30, 0x34, 0x12, 0x0d, 0x0a, 0x05, 0x75, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x22, 0x1c, 0x0a, 0x0b, 0x53, 0x63, 0x5f, 0x31, 0x30, 0x30, 0x32,
	0x30, 0x30, 0x30, 0x34, 0x12, 0x0d, 0x0a, 0x05, 0x75, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x22, 0x5e, 0x0a, 0x0b, 0x43, 0x73, 0x5f, 0x31, 0x30, 0x30, 0x32, 0x30, 0x30,
	0x30, 0x35, 0x12, 0x10, 0x0a, 0x08, 0x62, 0x61, 0x67, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0d, 0x12, 0x2a, 0x0a, 0x0a, 0x73, 0x65, 0x6c, 0x6c, 0x5f, 0x69, 0x74, 0x65,
	0x6d, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x73,
	0x73, 0x2e, 0x70, 0x62, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x49, 0x74, 0x65, 0x6d,
	0x12, 0x11, 0x0a, 0x09, 0x61, 0x73, 0x79, 0x6e, 0x5f, 0x66, 0x6c, 0x61, 0x67, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0d, 0x22, 0x8a, 0x01, 0x0a, 0x0b, 0x53, 0x63, 0x5f, 0x31, 0x30, 0x30, 0x32, 0x30,
	0x30, 0x30, 0x35, 0x12, 0x10, 0x0a, 0x08, 0x62, 0x61, 0x67, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0d, 0x12, 0x2a, 0x0a, 0x0a, 0x73, 0x65, 0x6c, 0x6c, 0x5f, 0x69, 0x74,
	0x65, 0x6d, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x63, 0x6f, 0x6d, 0x2e,
	0x73, 0x73, 0x2e, 0x70, 0x62, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x49, 0x74, 0x65,
	0x6d, 0x12, 0x11, 0x0a, 0x09, 0x61, 0x73, 0x79, 0x6e, 0x5f, 0x66, 0x6c, 0x61, 0x67, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0d, 0x12, 0x2a, 0x0a, 0x06, 0x72, 0x65, 0x77, 0x61, 0x72, 0x64, 0x18, 0x04,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x73, 0x73, 0x2e, 0x70, 0x62,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x5f, 0x52, 0x65, 0x77, 0x61, 0x72, 0x64, 0x32,
	0x22, 0x1a, 0x0a, 0x0b, 0x43, 0x73, 0x5f, 0x31, 0x30, 0x30, 0x32, 0x30, 0x30, 0x30, 0x36, 0x12,
	0x0b, 0x0a, 0x03, 0x73, 0x65, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x22, 0x1a, 0x0a, 0x0b,
	0x53, 0x63, 0x5f, 0x31, 0x30, 0x30, 0x32, 0x30, 0x30, 0x30, 0x36, 0x12, 0x0b, 0x0a, 0x03, 0x73,
	0x65, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d,
}

var (
	file_df_1002_proto_rawDescOnce sync.Once
	file_df_1002_proto_rawDescData = file_df_1002_proto_rawDesc
)

func file_df_1002_proto_rawDescGZIP() []byte {
	file_df_1002_proto_rawDescOnce.Do(func() {
		file_df_1002_proto_rawDescData = protoimpl.X.CompressGZIP(file_df_1002_proto_rawDescData)
	})
	return file_df_1002_proto_rawDescData
}

var file_df_1002_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_df_1002_proto_goTypes = []interface{}{
	(*PItem)(nil),          // 0: com.ss.pb.proto.PItem
	(*P_Reward2)(nil),      // 1: com.ss.pb.proto.P_Reward2
	(*P_Reward2_List)(nil), // 2: com.ss.pb.proto.P_Reward2_List
	(*P_Bag_Limit)(nil),    // 3: com.ss.pb.proto.P_Bag_Limit
	(*Sc_10020000)(nil),    // 4: com.ss.pb.proto.Sc_10020000
	(*Cs_10020001)(nil),    // 5: com.ss.pb.proto.Cs_10020001
	(*Sc_10020001)(nil),    // 6: com.ss.pb.proto.Sc_10020001
	(*Cs_10020002)(nil),    // 7: com.ss.pb.proto.Cs_10020002
	(*Sc_10020002)(nil),    // 8: com.ss.pb.proto.Sc_10020002
	(*Sc_10020003)(nil),    // 9: com.ss.pb.proto.Sc_10020003
	(*Cs_10020004)(nil),    // 10: com.ss.pb.proto.Cs_10020004
	(*Sc_10020004)(nil),    // 11: com.ss.pb.proto.Sc_10020004
	(*Cs_10020005)(nil),    // 12: com.ss.pb.proto.Cs_10020005
	(*Sc_10020005)(nil),    // 13: com.ss.pb.proto.Sc_10020005
	(*Cs_10020006)(nil),    // 14: com.ss.pb.proto.Cs_10020006
	(*Sc_10020006)(nil),    // 15: com.ss.pb.proto.Sc_10020006
}
var file_df_1002_proto_depIdxs = []int32{
	1, // 0: com.ss.pb.proto.P_Reward2_List.reward2:type_name -> com.ss.pb.proto.P_Reward2
	3, // 1: com.ss.pb.proto.Sc_10020000.bag_limits:type_name -> com.ss.pb.proto.P_Bag_Limit
	0, // 2: com.ss.pb.proto.Sc_10020001.items:type_name -> com.ss.pb.proto.PItem
	0, // 3: com.ss.pb.proto.Sc_10020002.items:type_name -> com.ss.pb.proto.PItem
	2, // 4: com.ss.pb.proto.Sc_10020003.reward2_list:type_name -> com.ss.pb.proto.P_Reward2_List
	0, // 5: com.ss.pb.proto.Cs_10020005.sell_items:type_name -> com.ss.pb.proto.PItem
	0, // 6: com.ss.pb.proto.Sc_10020005.sell_items:type_name -> com.ss.pb.proto.PItem
	1, // 7: com.ss.pb.proto.Sc_10020005.reward:type_name -> com.ss.pb.proto.P_Reward2
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_df_1002_proto_init() }
func file_df_1002_proto_init() {
	if File_df_1002_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_df_1002_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_df_1002_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*P_Reward2); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_df_1002_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*P_Reward2_List); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_df_1002_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*P_Bag_Limit); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_df_1002_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Sc_10020000); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_df_1002_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Cs_10020001); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_df_1002_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Sc_10020001); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_df_1002_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Cs_10020002); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_df_1002_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Sc_10020002); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_df_1002_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Sc_10020003); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_df_1002_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Cs_10020004); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_df_1002_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Sc_10020004); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_df_1002_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Cs_10020005); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_df_1002_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Sc_10020005); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_df_1002_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Cs_10020006); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_df_1002_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Sc_10020006); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_df_1002_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_df_1002_proto_goTypes,
		DependencyIndexes: file_df_1002_proto_depIdxs,
		MessageInfos:      file_df_1002_proto_msgTypes,
	}.Build()
	File_df_1002_proto = out.File
	file_df_1002_proto_rawDesc = nil
	file_df_1002_proto_goTypes = nil
	file_df_1002_proto_depIdxs = nil
}
